import React, { createContext, useContext, useState } from 'react';

type Language = 'ro' | 'ru';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  ro: {
    home: 'Acasă',
    models: 'Modele Ceasuri',
    about: 'Despre noi',
    companies: 'Companii',
    contact: 'Contact',
    corporateClocks: 'Ceasuri Corporate',
    privacy: 'Politica de confidențialitate',
    twelveSet: 'Setul Twelve',
    testimonials: 'Recenzii',
    heroTitle: 'Fiecare clipă acasă',
    heroSubtitle: 'devine mai frumoasă cu ceasurile Twelve',
    heroButton: 'Alege-ți ceasul preferat',
    viewModels: 'Vezi modelele',
    aboutBrandTitle: 'Suntem Twelve și dăm viață pereților tăi',
    aboutBrandText: 'Totul a început din dorința de a aduce un decor deosebit pe pereți, fără tablouri plictisitoare sau abțibilduri banale.',
    aboutBrandText2: 'Ceasurile Twelve, realizate din sticlă organică de calitate superioară, pot fi personalizate complet cu nume, inscripții sau logoul firmei tale, transformând fiecare perete într-un element unic.',
    twelveSetTitle: 'Setul Twelve – Tot ce ai nevoie pentru un ceas gata de perete',
    twelveSetText: 'Fiecare set Twelve include toate accesoriile necesare pentru instalare rapidă și ușoară, fără ajutorul unui meșter. Piesele vin cu bandă dublu-adezivă, iar suprafețele pieselor și ale acelor cu cerc au peliculă de proiecție, pentru a proteja finisajul până la montaj. Șablonul din hartie groasa, pe modelul si diametru solicitat, și instrucțiunea pas cu pas te ajută să montezi ceasul singur, transformând peretele tău în element unic și personalizat.',
    popularModelsTitle: 'Modele populare',
    viewAllModels: 'Vezi toate modelele',
    happyCustomers: 'Clienții noștri fericiți',
    testimonial1: 'Ceasul este superb, este în armonie perfectă cu interiorul! Dar... cel mai mult am rămas plăcut surprinsă de echipa Twelve Clocks! Receptivi, amabili și foarte plăcuți ca oameni! Vă mulțumesc frumos pentru serviciile acordate! Cu siguranță o să vă recomand ori de câte ori voi avea ocazia!',
    testimonial2: 'Recomand cu cea mai mare încredere — responsabili, punctuali și o atitudine foarte frumoasă față de clienți. Ca sfat: apelați cu instalarea la ei — un specialist se vede când pune mâna! Mulțumesc și vă doresc succese!',
    testimonial3: 'Foarte frumos ceasul. Băieții foarte receptivi în cazul în care ai nevoie de ajutor. Instrucțiunile clare, ceasul ușor de instalat și calitativ.',
    testimonial4: 'Ceasul este fenomenal, îmi place enorm! A schimbat complet interiorul odăii noastre. Livrare rapidă, echipă bine organizată. Mulțumim enorm! ❤️🌸👋👍',
    testimonial5: 'A ajuns ceasul! 😍 Sunt foarte încântată, mama căuta un astfel de model de 3 ani! Calitativ, preț accesibil, ambalat frumos și estetic. Mulțumesc mult!',
    contactCtaTitle: 'Comandă-ți ceasul acum!',
    contactCtaButton: 'Contactează-ne',
    footerTagline: 'Transformă peretele într-o operă de artă',
    followUs: 'Urmărește-ne',
    modelsPageTitle: 'Colecția noastră',
    modelsPageSubtitle: 'Descoperă ceasurile 3D care transformă orice spațiu',
    modelsContactTitle: 'Trimite-ne un mesaj pentru mai multe detalii',
    classic: 'Clasice',
    modern: 'Moderne',
    custom: 'Personalizate',
    corporateTitle: 'Ceasuri personalizate pentru companii',
    corporateSubtitle: 'Logo-ul companiei tale, integrat într-un ceas unic, premium și realizat manual.',
    aboutPageTitle: 'Despre Twelve',
    aboutPageSubtitle: 'Pasiunea noastră pentru design și timp',
    ourStory: 'Povestea noastră',
    ourStoryText: 'Totul a început din dorința de a aduce un decor deosebit pe pereți, fără tablouri plictisitoare sau abțibilduri banale. Așa am creat ceasurile Twelve, realizate din sticlă organică de calitate superioară, cu posibilitatea de personalizare completă: nume de familie, orice inscripție sau logoul firmei tale. Fiecare ceas transformă pereții într-un element unic și plin de personalitate.',
    howWeCreate: 'Cum creăm ceasurile Twelve?',
    step1Title: 'Design',
    step1Text: 'Fiecare ceas este creat cu grijă de designerul nostru și poate fi complet personalizat: inscripții, nume, logouri sau forme unice tăiate la laser.',
    step2Title: 'Producție',
    step2Text: 'Ceasurile Twelve sunt tăiate din sticlă organică reflectoare și realizate integral în Republica Moldova — de la piesele individuale până la asamblarea finală.',
    step3Title: 'Împachetare',
    step3Text: 'Setul Twelve include tot ce ai nevoie pentru instalare rapidă și independentă: șabloane, instrucțiuni pas cu pas și toate accesoriile necesare. Totul pentru o experiență simplă și plăcută.',
    companiesPageTitle: 'Ceasuri personalizate pentru companii',
    companiesPageSubtitle: 'Îți putem crea un ceas 3D cu logo-ul brandului tău',
    companiesBenefitsTitle: 'De ce să alegi Twelve pentru compania ta',
    benefit1Title: 'Design exclusiv',
    benefit1Text: 'Ceas personalizat cu logo-ul companiei tale',
    benefit2Title: 'Dimensiuni personalizabile',
    benefit2Text: 'Adaptăm dimensiunile pentru orice spațiu',
    benefit3Title: 'Cadou corporate ideal',
    benefit3Text: 'Perfect pentru birouri, recepții sau cadouri pentru clienți',
    requestQuote: 'Solicită o ofertă',
    contactPageTitle: 'Contactează-ne',
    contactPageSubtitle: 'Hai să transformăm timpul într-un decor unic pentru casa ta',
    getInTouch: 'Contactează-ne',
    name: 'Nume',
    email: 'Email',
    phone: 'Telefon',
    subject: 'Subiect (opțional)',
    message: 'Mesaj',
    send: 'Trimite',
    sending: 'Se trimite...',
    messageSent: 'Mulțumim pentru mesaj!',
    messageDescription: 'Echipa Twelve te va contacta în curând cu un răspuns.',
    error: 'Eroare',
    errorDescription: 'A apărut o eroare. Te rugăm să încerci din nou.',
    contactFormTitle: 'Hai să creăm ceva special împreună',
    address: 'Adresă',
    addressText: 'Chișinău, Moldova',
    privacyTitle: 'Politica de confidențialitate',
    privacyIntro: 'Confidențialitatea ta este prioritatea noastră. Această politică de confidențialitate explică modul în care colectăm, utilizăm și protejăm informațiile tale personale.',
    privacySection1Title: '1. Informațiile pe care le colectăm',
    privacySection1Text: 'Colectăm informații pe care ni le furnizezi direct, precum numele, adresa de email, numărul de telefon și detaliile comenzii atunci când plasezi o comandă sau ne contactezi.',
    privacySection2Title: '2. Cum folosim informațiile tale',
    privacySection2Text: 'Utilizăm informațiile tale pentru a procesa comenzile, a îmbunătăți serviciile noastre, a comunica cu tine și a-ți oferi suport clienți.',
    privacySection3Title: '3. Partajarea informațiilor',
    privacySection3Text: 'Nu vindem, închiriem sau partajăm informațiile tale personale cu terți, cu excepția cazului în care este necesar pentru procesarea comenzilor tale sau conform legii.',
    privacySection4Title: '4. Securitatea datelor',
    privacySection4Text: 'Implementăm măsuri de securitate pentru a proteja informațiile tale împotriva accesului neautorizat, modificării sau divulgării.',
    privacySection5Title: '5. Cookie-uri',
    privacySection5Text: 'Site-ul nostru poate utiliza cookie-uri pentru a îmbunătăți experiența ta de navigare și a analiza traficul pe site.',
    privacySection6Title: '6. Drepturile tale',
    privacySection6Text: 'Ai dreptul de a accesa, corecta sau șterge informațiile tale personale. Pentru orice solicitare, te rugăm să ne contactezi.',
    privacySection7Title: '7. Modificări ale politicii',
    privacySection7Text: 'Ne rezervăm dreptul de a actualiza această politică de confidențialitate. Orice modificare va fi publicată pe această pagină.',
    privacySection8Title: '8. Contact',
    privacySection8Text: 'Pentru întrebări sau preocupări legate de confidențialitate, ne poți contacta la adresa de email sau telefon afișată pe pagina de contact.',
  },
  ru: {
    home: 'Главная',
    models: 'Модели Часов',
    about: 'О нас',
    companies: 'Компании',
    contact: 'Контакт',
    corporateClocks: 'Корпоративные Часы',
    privacy: 'Политика конфиденциальности',
    twelveSet: 'Набор Twelve',
    testimonials: 'Отзывы',
    heroTitle: 'Каждый момент дома',
    heroSubtitle: 'становится прекраснее с часами Twelve',
    heroButton: 'Выберите свои часы',
    viewModels: 'Посмотреть модели',
    aboutBrandTitle: 'Мы Twelve и оживляем ваши стены',
    aboutBrandText: 'Всё началось с желания привнести особый декор на стены, без скучных картин или банальных наклеек.',
    aboutBrandText2: 'Часы Twelve, изготовленные из высококачественного органического стекла, можно полностью персонализировать именами, надписями или логотипом вашей компании, превращая каждую стену в уникальный элемент.',
    twelveSetTitle: 'Набор Twelve – Всё необходимое для готовых настенных часов',
    twelveSetText: 'Каждый набор Twelve включает все необходимые аксессуары для быстрой и легкой установки без помощи мастера. Детали поставляются с двусторонней клейкой лентой, а поверхности деталей и стрелок с кругом имеют защитную пленку для защиты покрытия до монтажа. Трафарет из плотной бумаги по запрашиваемой модели и диаметру, а также пошаговая инструкция помогут вам самостоятельно установить часы, превращая вашу стену в уникальный и персонализированный элемент.',
    popularModelsTitle: 'Популярные модели',
    viewAllModels: 'Посмотреть все модели',
    happyCustomers: 'Наши довольные клиенты',
    testimonial1: 'Часы великолепны, идеально гармонируют с интерьером! Но... больше всего меня приятно удивила команда Twelve Clocks! Отзывчивые, любезные и очень приятные люди! Большое спасибо за оказанные услуги! Обязательно буду рекомендовать при любой возможности!',
    testimonial2: 'Рекомендую с полной уверенностью — ответственные, пунктуальные и очень приятное отношение к клиентам. Совет: обращайтесь к ним за установкой — профессионала видно по работе! Спасибо и желаю успехов!',
    testimonial3: 'Очень красивые часы. Ребята очень отзывчивые, если нужна помощь. Инструкции понятные, часы легко установить и качественные.',
    testimonial4: 'Часы феноменальны, мне очень нравятся! Они полностью изменили интерьер нашей комнаты. Быстрая доставка, хорошо организованная команда. Огромное спасибо! ❤️🌸👋👍',
    testimonial5: 'Часы пришли! 😍 Я очень довольна, мама искала такую модель 3 года! Качественные, доступная цена, красиво и эстетично упакованы. Большое спасибо!',
    contactCtaTitle: 'Закажите свои часы сейчас!',
    contactCtaButton: 'Свяжитесь с нами',
    footerTagline: 'Превратите стену в произведение искусства',
    followUs: 'Следите за нами',
    modelsPageTitle: 'Наша коллекция',
    modelsPageSubtitle: 'Откройте для себя 3D часы, которые преобразят любое пространство',
    modelsContactTitle: 'Отправьте нам сообщение для получения дополнительной информации',
    classic: 'Классические',
    modern: 'Современные',
    custom: 'Персонализированные',
    corporateTitle: 'Персонализированные часы для компаний',
    corporateSubtitle: 'Логотип вашей компании, встроенный в уникальные, премиальные часы ручной работы.',
    aboutPageTitle: 'О Twelve',
    aboutPageSubtitle: 'Наша страсть к дизайну и времени',
    ourStory: 'Наша история',
    ourStoryText: 'Всё началось с желания привнести особый декор на стены, без скучных картин или банальных наклеек. Так мы создали часы Twelve, изготовленные из высококачественного органического стекла, с возможностью полной персонализации: фамилия, любая надпись или логотип вашей компании. Каждые часы превращают стены в уникальный и полный индивидуальности элемент.',
    howWeCreate: 'Как мы создаем часы Twelve?',
    step1Title: 'Дизайн',
    step1Text: 'Каждые часы тщательно создаются нашим дизайнером и могут быть полностью персонализированы: надписи, имена, логотипы или уникальные формы, вырезанные лазером.',
    step2Title: 'Производство',
    step2Text: 'Часы Twelve вырезаны из отражающего органического стекла и полностью изготовлены в Республике Молдова — от отдельных деталей до финальной сборки.',
    step3Title: 'Упаковка',
    step3Text: 'Набор Twelve включает всё необходимое для быстрой и самостоятельной установки: трафареты, пошаговые инструкции и все необходимые аксессуары. Всё для простого и приятного опыта.',
    companiesPageTitle: 'Персонализированные часы для компаний',
    companiesPageSubtitle: 'Мы можем создать для вас 3D часы с логотипом вашего бренда',
    companiesBenefitsTitle: 'Почему стоит выбрать Twelve для вашей компании',
    benefit1Title: 'Эксклюзивный дизайн',
    benefit1Text: 'Персонализированные часы с логотипом вашей компании',
    benefit2Title: 'Настраиваемые размеры',
    benefit2Text: 'Мы адаптируем размеры для любого пространства',
    benefit3Title: 'Идеальный корпоративный подарок',
    benefit3Text: 'Идеально для офисов, рецепций или подарков клиентам',
    requestQuote: 'Запросить предложение',
    contactPageTitle: 'Свяжитесь с нами',
    contactPageSubtitle: 'Давайте превратим время в уникальный декор для вашего дома',
    getInTouch: 'Свяжитесь с нами',
    name: 'Имя',
    email: 'Email',
    phone: 'Телефон',
    subject: 'Тема (необязательно)',
    message: 'Сообщение',
    send: 'Отправить',
    sending: 'Отправка...',
    messageSent: 'Спасибо за сообщение!',
    messageDescription: 'Команда Twelve свяжется с вами в ближайшее время.',
    error: 'Ошибка',
    errorDescription: 'Произошла ошибка. Пожалуйста, попробуйте снова.',
    contactFormTitle: 'Давайте создадим что-то особенное вместе',
    address: 'Адрес',
    addressText: 'Кишинёв, Молдова',
    privacyTitle: 'Политика конфиденциальности',
    privacyIntro: 'Ваша конфиденциальность является нашим приоритетом. Эта политика конфиденциальности объясняет, как мы собираем, используем и защищаем вашу личную информацию.',
    privacySection1Title: '1. Информация, которую мы собираем',
    privacySection1Text: 'Мы собираем информацию, которую вы нам предоставляете напрямую, такую как имя, адрес электронной почты, номер телефона и детали заказа, когда вы размещаете заказ или связываетесь с нами.',
    privacySection2Title: '2. Как мы используем вашу информацию',
    privacySection2Text: 'Мы используем вашу информацию для обработки заказов, улучшения наших услуг, общения с вами и предоставления поддержки клиентов.',
    privacySection3Title: '3. Передача информации',
    privacySection3Text: 'Мы не продаем, не сдаем в аренду и не передаем вашу личную информацию третьим лицам, за исключением случаев, необходимых для обработки ваших заказов или в соответствии с законом.',
    privacySection4Title: '4. Безопасность данных',
    privacySection4Text: 'Мы применяем меры безопасности для защиты вашей информации от несанкционированного доступа, изменения или раскрытия.',
    privacySection5Title: '5. Файлы cookie',
    privacySection5Text: 'Наш сайт может использовать файлы cookie для улучшения вашего опыта просмотра и анализа трафика сайта.',
    privacySection6Title: '6. Ваши права',
    privacySection6Text: 'Вы имеете право получать доступ, исправлять или удалять вашу личную информацию. Для любых запросов, пожалуйста, свяжитесь с нами.',
    privacySection7Title: '7. Изменения в политике',
    privacySection7Text: 'Мы оставляем за собой право обновлять эту политику конфиденциальности. Любые изменения будут опубликованы на этой странице.',
    privacySection8Title: '8. Контакт',
    privacySection8Text: 'По вопросам или проблемам, связанным с конфиденциальностью, вы можете связаться с нами по адресу электронной почты или телефону, указанным на странице контактов.',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('ro');

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations['ro']] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
